# Generated by Django 4.1.3 on 2023-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='skill',
            field=models.CharField(choices=[('plumber', 'plumber'), ('electrician', 'electrician'), ('mechanic', 'mechanic'), ('sweeper', 'sweeper'), ('house keeper', 'house keeper'), ('driver', 'driver'), ('other', 'other')], default='other', max_length=200),
        ),
    ]
