# Generated by Django 4.1.3 on 2023-04-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_category_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='skill',
        ),
    ]
